<?php

namespace Database\Seeders\Master;

use App\Models\Master\Designation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DesignationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            "Helper" => "IV",
            "Peon" => "IV",
            "Senior Khalasi" => "IV",
            "Heavy Duty Vehicle Driver" => "III",
            "Junior Engineer - II" => "II",
            "Lineman/Wireman - III" => "III",
            "Senior Assistant" => "III",
            "Plant Attendant GR-I" => "III",
            "Junior Engineer(Civil)" => "II",
            "Plant Operator Gr.I/Senior Technician" => "II",
            "Technician GR-II" => "III",
            "Junior Input/Output Assistant" => "III",
            "Plant Operator GR-II" => "III",
            "Daftery" => "IV",
            "Crane Operator" => "III",
            "Jr.Pharmacist" => "III",
            "Lineman" => "III",
            "Attendant" => "IV",
            "Plant Operator GR-I" => "III",
            "Electrician GR-I" => "III",
            "Technician GR-I" => "III",
            "Plant Attendant GR-III" => "III",
            "Deputy Superintendant (Estt)" => "III",
            "Senior Foreman" => "II",
            "Superintendant(Est)" => "II",
            "Senior Draughtsman" => "III",
            "Civil Mistry" => "III",
            "Electrician GR-II" => "III",
            "Plant Attendant GR-II" => "III",
            "Technician Gr-III/Fitter Gr-1" => "III",
            "Executive Engineer" => "I",
            "Kamdar" => "IV",
            "Chemist" => "II",
            "Fire Supervisor" => "III",
            "Store Keeper" => "III",
            "Watchman" => "IV",
            "Deputy Engineer" => "I",
            "Executive Engineer(Shift)" => "I",
            "Superintending Engineer" => "I",
            "Gardener" => "IV",
            "Deputy Superintendant (Accounts)" => "III",
            "Leading Fireman III" => "III",
            "Senior Electrician" => "III",
            "Carpenter" => "III",
            "Junior Assistant" => "III",
            "Fireman" => "IV",
            "S.B.O. Gr-II" => "IV",
            "Female Attendant" => "IV",
            "Mason" => "III",
            "Driver cum Operator III" => "III",
            "Plant Cleaning Supervisor" => "III",
            "Superintendant(A/c)" => "II",
            "Security Inspector" => "III",
            "Senior Welder" => "III",
            "Fitter GR-I" => "III",
            "Electrical Motor Winder GR I" => "III",
            "Chief Engineer" => "I",
            "Tool Room Assistant" => "III",
            "Machinist GR-I" => "III",
            "Plant Attendant GR-IV" => "III",
            "Assistant Chemist" => "III",
            "Deputy Chief Accounts Officer" => "I",
            "Plumber" => "III",
            "Superintendent(Accounts)" => "II",
            "Cleaner" => "IV",
            "Guest House Attendant" => "IV",
            "Sweeper" => "IV",
            "Additional Chief Engineer" => "I",
            "Stenographer" => "III",
            "Ronio Operator (LHP)" => "IV",
            "Leading Fireman IV" => "IV",
            "SR ELECTRICIAN CUM CRANE OPTR" => "III",
            "DE Operator" => "III",
            "Technician GR-IV - III" => "III",
            "Tracer" => "III",
            "Nurse" => "III",
            "Security Officer" => "II",
            "Artician GR-I" => "III",
            "Cable Jointer" => "III",
            "Driver GR-II" => "III",
            "Chief Medical Officer" => "I",
            "Senior Stenographer" => "II",
            "Chief Chemist" => "I",
            "Senior Manager (IT)" => "I",
            "Assistant Manager (IT)" => "II",
            "Lab Technician" => "III",
            "Data Entry Operator" => "III",
            "Superintending Engineer(Civil)" => "I",
            "Executive Engineer(Civil)" => "I",
            "Station Fire Officer" => "II",
            "Welder" => "III",
            "Fitter GR-II - IV" => "IV",
            "Dresser - III" => "III",
            "Junior Stenographer" => "III",
            "Artician GR-II" => "III",
            "Statistician" => "III",
            "Motor Mechanic" => "III",
            "Manager (IT)" => "I",
            "Male Attendant" => "IV",
            "Roino Operator" => "IV",
            "Additional Chief Engineer(Civil)" => "I",
            "Chief  Chemist Gr.I" => "I",
            "R.C.P" => "III",
            "Chief Chemist GR-II" => "I",
            "Helper Cum Kamdar" => "IV",
            "Assistant Secretary" => "II",
            "Personnel Officer" => "I",
            "Executive Director (Generation)" => "I",
            "Telecom Technician" => "III",
            "Junior Assistant(Typist)" => "III",
            "Instrument Mechanic" => "III",
            "Technician Gr-IV/Fitter Gr-II - III" => "III",
            "Deputy Engineer(Civil)" => "I",
            "Safety Officer" => "I",
            "Senior Safety Officer" => "I",
            "Technician (Telecom)" => "III",
            "Asst.Timekeeper (ADMIN)" => "III",
            "Deputy Safety Officer - II" => "II",
            "Deputy General Manager" => "I",
            "Additional General Manager" => "I",
            "Fuel Sample Collector" => "IV",
            "Controller of Accounts" => "I",
            "Fitter GR-II - III" => "III",
            "Khalasi" => "IV",
            "Driver" => "III",
            "Cook" => "IV",
            "Technician GR-III" => "III",
            "Instrument Mechanical Attendant" => "IV",
            "Senior Medical Officer" => "I",
            "Insrument Assistant" => "IV",
            "Chief Finance Manager" => "I",
            "Carrier Technician" => "III",
            "Deputy Safety Officer - I" => "I",
            "Jr Asst(Time Keeping)" => "III",
            "Law Officer" => "I",
            "Junior Engineer - III" => "III",
            "Machinist GR-III" => "III",
            "Wireman" => "III",
            "Industrial Relations Officer" => "I",
            "Technician (Instrumentation)" => "III",
            "Junior Assistant(LHP)" => "III",
            "Female Attendant(Admin)" => "IV",
            "Electrician" => "III",
            "Kamdar/Gardner" => "IV",
            "Machinist GR-II" => "III",
            "Technician GR-IV - IV" => "IV",
            "Lineman/Wireman IV" => "IV",
            "Jr. Asst. (Temp)" => "III",
            "Dresser - IV" => "IV",
            "Blue Printer" => "IV",
            "Civil Supervisor" => "III",
            "Deputy Engineer(Mines)" => "I",
            "Technician Gr-IV/Fitter Gr-II - IV" => "IV",
            "Medical Officer" => "I",
            "Line Inspector GR-II" => "III",
            "Accounts Officer" => "I",
            "Junior Assistant (TRA)" => "III",
            "Lab Tester" => "III",
            "Labour Welfare Officer" => "II",
            "Peon(Shift)" => "IV",
            "Deputy Engineer - II" => "II",
            "Vidyut Sahayak(Junior Engineer)" => "II",
            "Assistant Time Keeper" => "III",
            "Assistant Medical Officer" => "II",
            "Vidyut Sahayak (Plant Attendant-I)" => "III",
            "Company Secretary" => "I",
            "Vidyut Sahayak(Junior Assistant)" => "III",
            "Managing Director" => "II",
            "Vidyut Sahayak (Junior Engineer-Civil)" => "II",
            "Driver cum Operator IV" => "IV",
            "General Manager" => "I",
            "Apprentice ITI(COPA)" => "IV",
            "Apprentice ITI(Electrician)" => "IV",
            "Apprentice BOAT(Graduate-General Streams)" => "III",
            "Apprentice ITI(IMCP)" => "IV",
            "Apprentice ITI(Instrument Mech)" => "IV",
            "Apprentice ITI(Wireman)" => "IV",
            "Apprentice ITI(Fitter)" => "IV",
            "Apprentice ITI(Welder)" => "IV",
            "Apprentice BOAT(Diploma-I&C)" => "III",
            "Apprentice BOAT(Diploma-Mechanical)" => "IV",
            "Apprentice BOAT(Graduate-Electrical)" => "IV",
            "Apprentice BOAT(Graduate-Mechanical)" => "IV",
            "Apprentice BOAT(Diploma-Electrical)" => "IV",
            "Apprentice ITI(Machinist)" => "IV",
            "Apprentice ITI(Electronics Mech)" => "IV",
            "Apprentice ITI(Turner)" => "IV",
            "Apprentice BOAT(Graduate-Civil)" => "IV",
            "Apprentice ITI(MMCP)" => "IV",
            "Apprentice ITI(Mechanic-Diesel)" => "IV",
            "Apprentice ITI(Ref & Air-condi. Mech)" => "IV",
            "Apprentice BOAT(Graduate-E&C)" => "II",
            "Apprentice BOAT(Diploma-Civil)" => "IV",
            "Apprentice ITI(Plumber)" => "IV",
        ];

        foreach ($data as $designation => $class) {
            Designation::firstOrCreate([
                'name' => $designation,
                'class' => $class
            ]);
        }
    }
}
