<?php

namespace Database\Seeders\Master;

use App\Models\Master\Qualification;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QualificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            "7TH PASS",
            "1ST PASS",
            "3RD PASS",
            "4TH PASS",
            "illiterate",
            "2ND PASS",
            "Diploma (Mech.)",
            "8 TH PASS",
            "II Class Wireman",
            "HSC",
            "SSC",
            "ITI Electrician",
            "ITI Electronics Mech.",
            "II Class Boiler Compitiency",
            "Wireman Certificate",
            "Diploma (Civil)",
            "Diploma (Elect.)",
            "II Class Boiler Compitiency",
            "SSC Fail",
            "II Class Boiler Proficiency",
            "Diploma (Mech.)",
            "ITI Machinist",
            "ITI WIREMAN",
            "B.Com.",
            "First Class Electrical Supervisor",
            "9TH PASS",
            "ITI Fitter",
            "CME",
            "Diploma (Pharmacy)",
            "I Class Boiler Compitency",
            "CME",
            "5TH PASS",
            "SSC Fail",
            "II Class Wireman",
            "GCC(50WPM)",
            "ITI WIREMAN",
            "CEE",
            "ITI INST.MECH",
            "ITI Machinist",
            "GCC(60WPM)",
            "S.Y. B.Com",
            "ITI Draughtsman Civil",
            "ITI Radio & TV holders",
            "Diploma (Elect.)",
            "BE (Electronics)",
            "6 TH PASS",
            "AMIE ( MECH ENG )",
            "M B A (Fin.)",
            "II Class Boiler Proficiency",
            "ITI DIESEL MECH",
            "ITI",
            "Web designing HTML",
            "DHTML & Java",
            "Diploma in Chemist",
            "B.Sc",
            "B.A.",
            "LVD Licence",
            "Sub Officer's Course",
            "B.Sc",
            "Diploma in Material Management",
            "ITI Welder",
            "ITI Fitter",
            "SSC",
            "S.Y. B.Com",
            "Gujarati Type 20 WPM",
            "GCC",
            "English (50WPM)",
            "M. Com.",
            "F.Y. BA",
            "Fireman Course",
            "BE (I & C)",
            "Certificate Examination in Furniture Making",
            "Steam Turbine Operator",
            "Electrician Exam",
            "Gujarati Type 40 WPM",
            "Fireman Course",
            "HSC",
            "ITI Motor winding",
            "Electricial Supervisor",
            "Computer Consept Course",
            "Diploma (Electronoics)",
            "B.Sc (Home Sci.)",
            "Wireman Certificate",
            "Electrical Wireman",
            "F.Y. B.Com",
            "Boiler Attendent(Apprenticeship)",
            "F.Y. BA",
            "HDVD Licence",
            "BE (Elect.)",
            "ITI Electrician",
            "Sanitory Inspector Diploma",
            "Electric Service Technician",
            "ITI Radio-TV Mechanic",
            "RFM",
            "ITI (Ref. & A.C.)",
            "English (40WPM)",
            "Gujarati (40WPM)",
            "English Type 40 WPM",
            "B.Com.",
            "ITI Auto Repair",
            "Elect. Course",
            "Boiler Operation Engineer (Proficiency)",
            "First Class Electrical Supervisor",
            "M.Sc",
            "BE (Mech)",
            "M.A",
            "FIRST CLASS BOILER ATTENDANT CERTIFICATE OF COMPETENCY",
            "ITI Plumber",
            "Gujarati Type 25 WPM",
            "English Type 50 WPM",
            "Bsc.Chemistry",
            "M B A (HR)",
            "11 TH PASS",
            "Diploma ( Power Electronoics)",
            "Diploma (PM & HR)",
            "LLB Spl.",
            "80 WPM Eng. Steno",
            "Diploma (Electronoics)",
            "AMIE (ELECTRICAL ENG.)",
            "ITI D'man Mech.",
            "HP Welder Test",
            "I Class Boiler Compitency",
            "Certificate In Computing",
            "ITI Draughtsman Civil",
            "Hindi subject..(SSC)",
            "Diploma (Pharmacy)",
            "Diploma(Medical Technology)",
            "English Type 40 WPM",
            "ITI Turner",
            "Diploma (I&C)",
            "AMIE ( MECH ENG )",
            "Diploma in Refrigerator/AC",
            "LLB(Gen)",
            "ITI D'MAN",
            "MECHANICAL",
            "MBBS",
            "F.Y. B.Com",
            "B. Tech. (Mettallurgy)",
            "S.Y. BA",
            "Sub Officer's Course",
            "Diploma (Ind. Safety)",
            "M.Sc",
            "BE (Elect.)",
            "BE (Computer Engineering)",
            "HDVD Licence",
            "7TH PASS",
            "Post Graduate Diploma in Business Management",
            "MCA",
            "M.Sc(Micro)",
            "BE (Civil)",
            "Diploma (Civil)",
            "Station Officer & Instructed Course",
            "56th Divisional Officer's Course",
            "GCC(60WPM)",
            "B.A.",
            "Diploma (Medical Technology)",
            "ITI Mechanic",
            "BE (Environment)",
            "Diploma in Electro & Radio",
            "PG Dip in Management",
            "English Short-hand(100WPM)",
            "GNM",
            "ITI INST",
            "Diploma in Midwifery",
            "GNM",
            "ITI DIESEL MECH",
            "Sahitya Sudhakar Exam",
            "BE (Electronics & Telecommunication)",
            "B. Tech. (Mech.)",
            "Energy Manager",
            "ADV.DPLOMA IN COMP. INTEGRATED MANUFACTURING",
            "Diploma in Computer Integrated Manufacturing",
            "BE (Mech)",
            "Certificate in Personal Computer Software",
            "Post Diploma in Industrial Electronics",
            "Advanced Certificate in Power Distribution Management",
            "Diploma (I&C)",
            "Turner",
            "Diploma (Electronics & Comm.)",
            "Diploma (Electronics & Comm.)",
            "Computer Consept Course",
            "PDDC BE(Mech)",
            "M B A (Financial Management)",
            "Elect. Course",
            "Swith Board Attendent",
            "B.Sc (Micro)",
            "Diploma (Automobile)",
            "BE (Computer & Science)",
            "MSW",
            "ITI Motor Mechanic",
            "Driving License",
            "ITI General Mechanic",
            "BA(HINDI)",
            "ITI Mechanic",
            "S.Y. BA",
            "MLW",
            "MSW",
            "PDDC BE(Elect)",
            "MCA",
            "M.B.A (Operations Management)",
            "Post diploma Degree Course in Elect.Engg",
            "Diploma In Lab.Studies",
            "Dip. In Strategic HRM",
            "Dip.In Lab.Practice",
            "BE (Electronics & Comm.)",
            "English (60WPM)",
            "Hindi (25WPM)",
            "FIRST CLASS BOILER ATTENDANT CERTIFICATE OF COMPETENCY",
            "ITI Welder",
            "Hindi Tisri Exam",
            "Gujarati Type 25 WPM",
            "MIDWIFE",
            "M B A (Project Management)",
            "Diploma(Inst.Mech.)",
            "Post Diploma in Industrial Safety",
            "B. Tech. (Elect.)",
            "Energy Auditor",
            "ITI D'MAN",
            "MECHANICAL",
            "AMIE (ELECTRICAL ENG.)",
            "B. Tech. (Elect.)",
            "ADV",
            "DIPLOMA IN INFO.TECH.",
            "M.Tech.",
            "Programme in Power Management",
            "Diploma Computer Application",
            "MLW",
            "PG Dip in HRD",
            "IBR Welder",
            "SLC",
            "ME (Elect.)",
            "ICWA",
            "BE (Mettallurgy)",
            "Steam Turbine Operator",
            "B.Ed",
            "D.P.Ed.",
            "NURSING",
            "NURSING",
            "Certificate Course in Industrial Health",
            "B.Sc (Chem Engg)",
            "ITI INST.MECH",
            "M. Com.",
            "Diploma (Mgt.)",
            "Diploma (I/T)",
            "PGDHRM",
            "BA(HINDI)",
            "M B A (HR)",
            "BE (INST.)",
            "ITI Electronics Mech.",
            "M.B.A (Operations Management)",
            "BE (Elect. & Electronics)",
            "MBA (Business Administration)",
            "Hindi Rashtrabhasa Parichaya",
            "B.E. (P.D.I.S.)",
            "M B A (Financial Management)",
            "PG Dip in Industrial Relations & Personnel Management",
            "M.B.A (HRM)",
            "POST DIPLOMA IN COMP.APPLI.",
            "DIPLOMA IN ELECTRICAL SERVICE TECHNICIAN",
            "ME (Mech)",
            "Elect. Motor Rewind",
            "BCA",
            "POST  DIPLOMA IN COMPUTER APPLICATIONS",
            "Boiler Attendent(Apprenticeship)",
            "B.E.(I/C)",
            "Chartered Accountant",
            "Chartered Accountant",
            "Diploma (IRPM)",
            "Diploma (IRPM)",
            "MBA(Power Management)",
            "MHRD",
            "ITI Boiler Attencent",
            "Diploma (Buisness Administration)",
            "Hindi Tisri Exam",
            "B.Tech. (Electronics & Comm.)",
            "ADVANCE DIPLOMA IN INFORMATION TECHNOLOGY",
            "Electrical Instal. Wiring & Joining",
            "M.Sc (CA & IT)",
            "BCA",
            "Energy Manager",
            "M.Tech.(Electrical)",
            "Hindi Dusri Exam",
            "B. Tech. (Mech.)",
            "ME (Elect.)",
            "BOILER WELDER",
            "Kovid",
            "ME (Mech)",
            "Hindi Vinit Exam",
            "M B A (Marketing)",
            "M.A",
            "B. Tech ( I & C)",
            "BE (Mech) Part time",
            "ITI Boiler Attencent",
            "BE (Electronics & Comm.)",
            "Data Entry Operator",
            "B.Ed",
            "Electrician Exam",
            "Professional Education Examination Part II",
            "Information Systems Audit (ISA)",
            "Diploma In Taxation Laws & Practice",
            "M B A (Fin.)",
            "Driver cum Operator Course",
            "ITI INST",
            "Bachlor (Pharmacy)",
            "Course on Good & Services Tax (GST)",
            "BBA",
            "ME (Civil)",
            "B.P.Ed.",
            "Art Teacher's Diploma",
            "ITI Armature Winding",
            "MBA (Business Administration)",
            "B. Tech. (Elect. & Electronics)",
            "B. Tech ( Civil)",
            "M.Tech. (Power Systems)",
            "B. Tech ( Civil)",
            "Diploma In Labour Laws & Practice",
            "B. Tech. (Chemical Engineering)",
            "Typewriting (50 WPM)",
            "Diploma in Petro Chemical Technology",
            "BE (Chemical)",
            "Bechlor of Rural Studies",
            "BE (I & C)",
            "B. Tech ( I & C)",
            "Certificate Course of Electrician",
            "Diploma Mechanical Engineering (D.L.M)",
            "Bachelor Of Physiotherapy",
            "M.Tech.",
            "CMA (Inter)",
            "BE (Electronics & INST.)",
            "AMIE (Civil Engineering)",
            "BE (Civil)",
            "M.sc Chemistry",
            "Certificate in Computer Concepts",
            "Bachlor (Pharmacy)",
            "M.sc Chemistry",
            "Bsc.Chemistry",
            "Certificate in Computer Concepts",
            "Diploma in Computer Programming",
            "MD",
            "BACHELOR OF SOCIAL WORK (BSW)",
            "MHRM",
            "B.E.(I/C)",
            "PROFESSIONAL PROGRAMME EXAMINATION",
            "Diploma (HRM)",
            "Doctor of Philosophy (Human Resource)",
            "LL.M (Business Law)",
            "M.Tech. (Mech.)",
            "Post Graduate Diploma in Environment and Sustainable Development",
            "B.Tech. (Electronics & Comm.)",
            "Bsc (Honours)",
            "MSC (Agriculture)",
            "Hindi subject..(SSC)",
            "BBA",
            "M B A (Marketing)",
            "ME (Elect.-Industrial Electronics)",
            "B.Sc (Elect. Engg.)",
            "ME (Elect.- Automatic Control & Robotics)",
            "BE (Mettallurgy)",
            "MBA (Maritime Management)",
            "MBBS",
            "B.Sc (Nursing)",
            "B.Sc (Nursing)",
            "B.Sc (Micro)",
            "M.Sc(Micro)",
            "Bsc (Honours)",
            "M.Tech. (Civil)",
            "M.Sc(Nursing)",
            "BE (Electronics)",
            "Company Secretary",
            "B.H.M.S.",
            "Diploma (Computer)",
            "BE (Computer)",
            "BE (IT)",
            "BE (IT)",
            "ME (Power Electronics)",
            "BE (Elect. & Electronics)",
            "CMA",
            "ME (Electronics & Communications)",
            "ME (CME)",
            "ME (Civil)",
            "BE (Electronics & INST.)",
            "CA (INTER)",
            "MBA (Project)",
            "M. Ed",
            "ITI (COPA)",
            "BE (Computer Engineering)",
            "B.Tech. (Computer Engineering)",
            "BE (Computer)",
        ];

        foreach ($data as $qualification) {
            # code...
            Qualification::firstOrCreate([
                'name' => $qualification,
            ]);
        }
    }
}